console:
  color:
    ask: 'blue'
    cmd: 'magenta'
    info: 'cyan'
    pass: 'green'
    warn: 'yellow'
    fail: 'red'

fact:
  uri: https://api.icndb.com/jokes/random

git:
  searchPaths:
    - C:\code\gtfs

gitTfs:
  cloneDir: C:\code\gtfs
  workspaceDir: C:\code\ws

msBuild:
  default:
    action: Build
    verbosity: Quiet
    maxThreads: 8
    buildConfig: Debug
    buildInParallel: true
    useEnv: true
    useSharedCompilation: false
    logsPath: C:\code\logs\msbuild
  print:
    warnings: false
    errors: true
  filePath:
    2015: C:\Program Files (x86)\MsBuild\14.0\Bin\MSBuild.exe
    2017: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MsBuild\15.0\Bin\MSBuild.exe
    2019: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MsBuild\15.0\Bin\MSBuild.exe
    latest: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MsBuild\Current\Bin\MSBuild.exe
  searchPaths:
    - C:\code\gtfs

sqlPackage:
  filePath:
    2017: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140\sqlpackage.exe
    latest: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\sqlpackage.exe

vsDevCmd:
  filePath:
    2015: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat
    2017: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\VsDevCmd.bat
    2019: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\VsDevCmd.bat
    latest: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\VsDevCmd.bat
